import { VERSION } from '@skillsmith/core';
import { CURRENT_COMMAND_SPECS } from '../spec/registry.ts';
import type { CommandSpecInput } from '../spec/types.ts';
import {
  COMMAND_GROUP_HEADINGS,
  OPTION_HELP_FAMILY_ORDER,
  OPTION_HELP_HEADINGS,
  workflowsForSpec,
} from './render.ts';
import { HELP_TOPIC_NAMES } from './topics.ts';

const commandName = (spec: CommandSpecInput): string => spec.path.slice('skillsmith '.length);

const renderCommand = (spec: CommandSpecInput): string => {
  const aliases =
    spec.aliases.length > 0
      ? `\nAliases: ${spec.aliases.map((alias) => `\`${alias}\``).join(', ')}\n`
      : '';
  const workflows = workflowsForSpec(spec)
    .map(
      (workflow) =>
        `- **${workflow.label}** (${workflow.safety}): ${workflow.description} — \`${workflow.invocation}\``,
    )
    .join('\n');
  const argumentsSection =
    spec.arguments.length === 0
      ? []
      : [
          '#### Arguments',
          '',
          ...spec.arguments.map((argument) => {
            const term = `${argument.required ? '<' : '['}${argument.name}${argument.variadic ? '...' : ''}${argument.required ? '>' : ']'}`;
            return `- \`${term}\` — ${argument.description}`;
          }),
          '',
        ];
  const optionGroups = OPTION_HELP_FAMILY_ORDER.flatMap((family) => {
    const options = spec.options.filter(
      (option) => (option.helpFamily ?? 'automation-output') === family,
    );
    if (options.length === 0) return [];
    return [
      `#### ${OPTION_HELP_HEADINGS[family].replace(/:$/u, '')}`,
      '',
      ...options.map(
        (option) =>
          `- \`${option.flags}\`${option.helpLevel === 'advanced' ? ' _(advanced)_' : ''} — ${option.description ?? ''}`,
      ),
      '',
    ];
  }).join('\n');
  return [
    `### \`${commandName(spec)}\``,
    '',
    spec.description,
    aliases,
    `Primary question: ${spec.primaryQuestion}`,
    '',
    `Minimal invocation: \`${spec.minimalInvocations?.[0] ?? spec.examples[0] ?? spec.path}\``,
    '',
    '#### Common workflows',
    '',
    workflows,
    '',
    ...argumentsSection,
    optionGroups,
    '#### Exit codes',
    '',
    ...(spec.exitCodes ?? []).map(({ code, meaning }) => `- \`${code}\` — ${meaning}`),
    '',
  ].join('\n');
};

export const renderCommandReference = (
  specs: readonly CommandSpecInput[] = CURRENT_COMMAND_SPECS,
  version: string = VERSION,
): string => {
  const publicSpecs = specs
    .filter((spec) => spec.path.split(' ').length === 2)
    .toSorted(
      (left, right) =>
        (left.helpOrder ?? Number.MAX_SAFE_INTEGER) - (right.helpOrder ?? Number.MAX_SAFE_INTEGER),
    );
  const groups = Object.keys(COMMAND_GROUP_HEADINGS) as (keyof typeof COMMAND_GROUP_HEADINGS)[];
  const body = groups.flatMap((group) => {
    const commands = publicSpecs.filter((spec) => spec.group === group);
    if (commands.length === 0) return [];
    return [
      `## ${COMMAND_GROUP_HEADINGS[group].replace(/:$/u, '')}`,
      '',
      ...commands.flatMap((spec) => [renderCommand(spec), '']),
    ];
  });
  return [
    '<!-- Generated by scripts/generate-command-reference.ts. -->',
    '',
    '# SkillSmith command reference',
    '',
    `Current version: \`${version}\``,
    '',
    'This reference is generated from the same command registry used by the parser and help output.',
    '',
    '## Help topics',
    '',
    HELP_TOPIC_NAMES.map((topic) => `- \`${topic}\``).join('\n'),
    '',
    ...body,
  ].join('\n');
};
