import type { CompletionNode } from './types.ts';

const flagTokens = (n: CompletionNode): string[] => {
  const tokens: string[] = [];
  for (const o of n.options) {
    if (o.long) tokens.push(o.long);
    if (o.short) tokens.push(o.short);
  }
  return tokens;
};

export const renderBash = (nodes: readonly CompletionNode[]): string => {
  const root = nodes[0];
  if (!root) return '';
  const bin = root.name;
  const subs = root.subcommands.map((s) => s.name);

  const caseArms: string[] = [];
  for (const sub of root.subcommands) {
    const subFlags = flagTokens(sub);
    const subArgChoices = sub.args.flatMap((a) => a.choices ?? []);
    const enumValues = new Set<string>(subArgChoices);
    for (const o of sub.options) for (const c of o.choices ?? []) enumValues.add(c);
    const words = [...subFlags, ...enumValues];
    caseArms.push(
      `      ${sub.name})\n        COMPREPLY=( $(compgen -W "${words.join(' ')}" -- "$cur") )\n        return 0;;`,
    );
  }

  const rootFlags = flagTokens(root);
  const rootWords = [...subs, ...rootFlags];

  return [
    '# skillsmith bash completion (autogenerated)',
    `# To install: ${bin} completion bash | sudo tee /etc/bash_completion.d/${bin}`,
    '',
    `_${bin}() {`,
    '  local cur prev sub i',
    '  COMPREPLY=()',
    `  cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `  prev="\${COMP_WORDS[COMP_CWORD-1]}"`,
    '  sub=""',
    '  for (( i=1; i<COMP_CWORD; i++ )); do',
    `    if [[ "\${COMP_WORDS[i]}" != -* ]]; then sub="\${COMP_WORDS[i]}"; break; fi`,
    '  done',
    '  case "$sub" in',
    ...caseArms,
    '    *)',
    `      COMPREPLY=( $(compgen -W "${rootWords.join(' ')}" -- "$cur") )`,
    '      return 0;;',
    '  esac',
    '}',
    `complete -F _${bin} ${bin}`,
    '',
  ].join('\n');
};
