import type { CompletionNode } from './types.ts';

const fishEscape = (s: string): string => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");

export const renderFish = (nodes: readonly CompletionNode[]): string => {
  const root = nodes[0];
  if (!root) return '';
  const bin = root.name;
  const lines: string[] = [
    '# skillsmith fish completion (autogenerated)',
    `# To install: ${bin} completion fish > ~/.config/fish/completions/${bin}.fish`,
    '',
  ];

  for (const sub of root.subcommands) {
    lines.push(
      `complete -c ${bin} -f -n '__fish_use_subcommand' -a ${sub.name} -d '${fishEscape(sub.description || sub.name)}'`,
    );
    for (const opt of sub.options) {
      const flagParts: string[] = [];
      if (opt.short) flagParts.push(`-s ${opt.short.replace(/^-/, '')}`);
      if (opt.long) flagParts.push(`-l ${opt.long.replace(/^--/, '')}`);
      const flag = flagParts.join(' ');
      if (!flag) continue;
      const choices = opt.choices ? ` -xa '${opt.choices.join(' ')}'` : '';
      const desc = opt.description ? ` -d '${fishEscape(opt.description)}'` : '';
      lines.push(
        `complete -c ${bin} -f -n '__fish_seen_subcommand_from ${sub.name}' ${flag}${choices}${desc}`,
      );
    }
    for (const arg of sub.args) {
      if (!arg.choices) continue;
      lines.push(
        `complete -c ${bin} -f -n '__fish_seen_subcommand_from ${sub.name}' -xa '${arg.choices.join(' ')}'`,
      );
    }
  }
  lines.push('');
  return lines.join('\n');
};
