import type { CompletionNode } from './types.ts';

const zshEscape = (s: string): string => s.replace(/'/g, "'\\''");

export const renderZsh = (nodes: readonly CompletionNode[]): string => {
  const root = nodes[0];
  if (!root) return '';
  const bin = root.name;

  const subLines = root.subcommands
    .map((s) => `    '${s.name}:${zshEscape(s.description || s.name)}'`)
    .join('\n');

  const caseArms = root.subcommands
    .map((s) => {
      const flags = s.options.flatMap((o) => {
        const names = [o.short, o.long].filter((n): n is string => Boolean(n));
        return names.map((n) => `'${n}[${zshEscape(o.description || n)}]'`);
      });
      const positionals = s.args
        .filter((a) => a.choices)
        .map((a) => `':${a.name}:(${(a.choices ?? []).join(' ')})'`);
      const enumPairs = s.options
        .filter((o) => o.choices)
        .map((o) => `'${o.long}=(${(o.choices ?? []).join(' ')})'`);
      const body = [...flags, ...positionals, ...enumPairs].join(' \\\n          ');
      return `    ${s.name})\n        _arguments \\\n          ${body || "':no-args:'"}\n        ;;`;
    })
    .join('\n');

  return [
    `#compdef ${bin}`,
    '# skillsmith zsh completion (autogenerated)',
    `# To install: ${bin} completion zsh > "\${fpath[1]}/_${bin}"`,
    '',
    `_${bin}() {`,
    '  local -a commands',
    '  commands=(',
    subLines,
    '  )',
    '  local context state state_descr line',
    '  _arguments -C \\',
    `    '1: :->cmd' \\`,
    `    '*::arg:->args'`,
    `  case "$state" in`,
    `    cmd) _describe 'command' commands ;;`,
    `    args) case "$line[1]" in`,
    caseArms,
    '    esac ;;',
    '  esac',
    '}',
    `_${bin} "$@"`,
    '',
  ].join('\n');
};
