import type { CompletionNode, CompletionOption } from './types.ts';

// Escape single quotes (outer single-quoted string) and colons (zsh _arguments
// / _describe delimiter) so description text can safely contain either.
const zshEscape = (s: string): string => s.replace(/'/g, "'\\''").replace(/:/g, '\\:');

const optionSpecs = (o: CompletionOption): string[] => {
  const desc = zshEscape(o.description || o.long || o.short || '');
  const choices = o.choices ? `:value:(${(o.choices ?? []).join(' ')})` : '';
  const longPart = o.long ? [`'${o.long}${o.choices ? '=' : ''}[${desc}]${choices}'`] : [];
  const shortPart = o.short ? [`'${o.short}[${desc}]${choices}'`] : [];
  return [...longPart, ...shortPart];
};

export const renderZsh = (nodes: readonly CompletionNode[]): string => {
  const root = nodes[0];
  if (!root) return '';
  const bin = root.name;

  const subLines = root.subcommands
    .map((s) => `    '${s.name}:${zshEscape(s.description || s.name)}'`)
    .join('\n');

  const caseArms = root.subcommands
    .map((s) => {
      const flags = s.options.flatMap(optionSpecs);
      const positionals = s.args
        .filter((a) => a.choices)
        .map((a) => `':${a.name}:(${(a.choices ?? []).join(' ')})'`);
      const body = [...flags, ...positionals].join(' \\\n          ');
      return `    ${s.name})\n        _arguments \\\n          ${body || "':no-args:'"}\n        ;;`;
    })
    .join('\n');

  return [
    `#compdef ${bin}`,
    '# skillsmith zsh completion (autogenerated)',
    `# To install: ${bin} completion zsh > "\${fpath[1]}/_${bin}"`,
    '',
    `_${bin}() {`,
    '  local -a commands',
    '  commands=(',
    subLines,
    '  )',
    '  local context state state_descr line',
    '  _arguments -C \\',
    `    '1: :->cmd' \\`,
    `    '*::arg:->args'`,
    `  case "$state" in`,
    `    cmd) _describe 'command' commands ;;`,
    `    args) case "$line[1]" in`,
    caseArms,
    '    esac ;;',
    '  esac',
    '}',
    `_${bin} "$@"`,
    '',
  ].join('\n');
};
