import { describe, expect, test } from 'bun:test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { buildProgram } from '../../../packages/cli/src/program.ts';

const ROOT = resolve(import.meta.dir, '..', '..', '..');

describe('EWP-P6-TS04', () => {
  test('generated README/reference output closes against the live command tree', async () => {
    const generatorPath = '../../../scripts/generate-command-reference.ts';
    const [reference, readme, generator] = await Promise.all([
      readFile(resolve(ROOT, 'docs/commands.md'), 'utf8'),
      readFile(resolve(ROOT, 'README.md'), 'utf8'),
      import(generatorPath) as Promise<Record<string, unknown>>,
    ]);
    expect(typeof generator.renderCommandReference).toBe('function');
    expect(typeof generator.checkCommandReference).toBe('function');
    expect(reference).toStartWith('<!-- Generated by scripts/generate-command-reference.ts. -->');
    expect(readme).toContain('<!-- skillsmith-command-index:start -->');
    expect(readme).toContain('<!-- skillsmith-command-index:end -->');
    for (const command of buildProgram().commands) {
      expect(reference, command.name()).toContain(`\`${command.name()}\``);
      for (const alias of command.aliases()) expect(reference, alias).toContain(`\`${alias}\``);
    }
  });
});
